# Generated by Django 4.0.5 on 2022-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_articles_date_alter_articles_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commands',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='commands',
            name='field',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Everyone'), (2, 'DJ'), (3, 'Premium')], default=1),
        ),
    ]
