# Generated by Django 4.0.5 on 2022-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_commands_is_premium_commands_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='field',
            field=models.CharField(choices=[('1', 'Everyone'), ('2', 'DJ'), ('3', 'Premium')], default='1', max_length=50),
        ),
    ]
