# Generated by Django 4.0.6 on 2022-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_commands_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.JSONField(),
        ),
    ]
